notifications:
  webhooks:
    - https://webhook.commit-email.info/

dist: xenial

env:
  global:
    DISPLAY: ":99.0"

rvm:
  - 2.4
  - 2.5
  - 2.6

gemfile:
  - gemfiles/rails6.gemfile
  - gemfiles/rails5.gemfile
  - gemfiles/rails5.1.gemfile
  - gemfiles/rails5.1-without-puma.gemfile

addons:
  apt:
    packages:
      - chromium-chromedriver
